version: "2.1"
services:
  benchmark:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/home/benchmark/driver
    command: /bin/bash -c "source ~/.bash_profile && benchmark-driver.ruby2.4 example.yml -o gruff --rbenv 'jruby-9.2.1.0-dev;jruby-9.2.0.0;system'"
